source 'https://rubygems.org'

gem 'cucumber',           '~> 5.2.0'
gem 'rspec',              '~> 3.10.0'
gem 'capybara',           '~> 3.34.0'
gem 'selenium-webdriver', '~> 3.142.7'
gem 'httparty',           '~> 0.18.1'
gem 'pry',                '~> 0.13.1'
gem 'json',               '~> 2.1.0'
gem 'parallel_tests',     '~> 3.4.0'
gem 'parallel',           '~> 1.20.1'
gem 'colorize',           '~> 0.8.1'
gem 'faker',              '~> 2.15.1'
gem 'rails',              '~> 6.1.3.1'
